### ISSUE TITLE
Tutorial code from flems.io doesn't work with Mithrill 2.0

### ISSUE THREAD

**Issue by ghost** [MithrilJS/mithril.js#2402]
Hey!

If I try to reproduce the tutorial app using the code from **flems.io** I get an error `mithril.withAttrs` is not a function. When I use the same code from [mithrill.js.org](https://mithril.js.org/simple-application.html) everything works just fine. As it turns out the code on **flems.io** is not updated to work with Mithrill 2.0.

Here's the [link](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcICqkBOAxA9tgLYB0AVmCADQgBmAljJagNqgB2AhkRGpjgFl8SaOUo1Y+doml8Abp2wACLBGUBeJcAA67JfqVR6YeKiUsAulV0HD+TkgAyx00toBXdgnpSAFAEotG1sDbAh4d2w9UjCAR3cIE18dPRC0nngAC2EzbRAAcQBRABU861S020ioXJBM+HgABzBUAHpWsKIAWjCTLs5G+hJMtXwAa3cBxpJJIlaB+lb3HDAy4MqDAHd6LIBhMJFpek4oFqV4bATyjYBff3WQkiyIdl8PL3gfV973KHhAlIbWyqbAkIwmJSaH5-EhITjwTgPWx3B43coPWCRMLSMzANEPKD2JBmd7ePz0JAApGhcKRaIkOIJJKAoH6DLZYlKPJFUrUalpaq1epNFrtTo9RLwfqDYajCZTGb4OYLJYrVp5JQAaiUFOurKU2z2BxenxOZwuV35ShRFUez1epM+fmh-yCto2IJmWJNkKULqtNuR6NtYE4cggJM8ZNeVPdNIiUSUMQg8UlySttnZOS5IAAChheXrWYKc8Lmm0OhBur0pQtZdhxpNGtNZvNBqq1GB1SAtSocF7sNj4CRdRmDHCEWZPZjByai0DDZl9sgTcdTmYLRB58j7rabrobiA0RxuLx0CDnCYxNQQJJpCb5Io+2pL-BfSz9FJ6OwdlP+4SHFfec5HoCBNkjD4vgCN0NjCBNol8PISGWNQunBeAymfUF0JIIgBjeKMnVeFDsFjfU-VpRMiEQkBOGQnA0JcLodirTDgEyMJaFqVpkB2btexIkckCoJQpFgMJ4QjJMGXwdxEDBb8xjRJRBIYbATAAOVPXsNQ1bVBKgThNNPXdbn8UyDH3dhD2PEAuB4PgQQIYhrwkKQZHgR9lCcwgiHfB4vx-VxHSguR2GECAAU9ACkF8MKIpIeELjAIT-HxW0QLAiDo2gj8Qjgukkxo2hfLYsc0ikMB3AAIyIX83EIqDIpg8jKggEhGjCcNpAAEQgWhOF+eAAnKoFPVDcMRrjVkrPI5SWFG6i8kM6rRBW6BMLyXB6HUt97IgPJ-G3SolpAb9Gjkkd2Au+AWHgABPRoIHURAAA94AsFhGkM2AIGyKARGwdRtt2pR9osMrpqBQKbrMUhFwAQQabAaIUKAEkwkK-DRhIov7GchxINTjJ4X0cYgO5jtZcm-zUAdCeJ+AtJ4UbKcWmj1qgMFOFWqBNpARwjL209DqpkJTvOy7Jdu77OF+-7AfUQWIXByHWoMGG5LhkhEeR1GTgx6gGsg7GDea4Bp29aRuZJiAybNtmoY2GmsPpk0baZkWncso72byaq5PgKQSADhopDux7nqq2qdgho28gAZTDA6QF9qGLAs-QrJsqgTwc9BBfu2ThwoG87w8rylEL4v-Iy0DwONnL4pEMjKgKqiaLw79uaLuTMIW722Rorg5Fwl53H70bMxoxEjby9WOP6swAHJWnQ5exdZMSJMQbWGzk9qjHYMYp8skS8hBVZU9GjPN4MU7IGjTDm-a2BMkYJBsUzkIM9RA8j1znZU8fAFSlzcveWQ6AYjF3ap1fq9BXq+GXgAYmXruaBB9fBIHwJiHg1tqrCHuufEAa8XBqwMHkUhJg8i4itNiQG2UiK5VGu3BC1c5IiWopfOEYBXzmQDKieclDeLwFaKgCkNCWppHoWoRhoVwotykUCVhRV2HwE4b4HyxARIv0SsjMA-CoazTPgefwN5IAwGjMwEAABWVAABOABeczwgBmGAcQt53IPnQAQpARCro3SoCHQOUgtAlRxOFYgJwlAAEYABsjRXpKAAGpqDhFwAA3HhbAABzb8ZgABMAAGRJVldA9xrsAbJeT2CoBiSUpJg0g5ZM4K9Lo2wkBZDqUUnpiSMlWTHuwdwWhqn5KKUocZABmBp-TdDlJIoxCEwB0JdBMPdGAqBwrsAgC03JYyJmxJmY0BwSBvw5NQEU2Z7B6KoRWSxPywBqpyzGDk-e7BiTIIGl8zgGSCHYAYTExJSgwD4CMEgJQyCkBQoyZIQk2BUDIMmUijJpywCy3uqgaqhJYBjF2TUi5BzAWvQyccqFZzUAAA4gUxJsX0t6UoRCSGwPCL4mypA7IGQsu5iAiCoGyOGZQwB6VdEZYQFlUhUCeEBkfDlczrmcy0Ki9FmLsW4tGbU8Z4zaXEoGdLLQfyAVApBWCiFUKkC-MIIDHoDh6DLFQJMvpBC2lgHoAAL3JQa1CTqUXGGVVinBarFD4s1YcvppLTnsHOfU6l2qMkdK6fUopABSK5wSw56Eec815sl3kIogPmi1-zZFEuBaCikproWeuwNa05dqHXEthYQBFSLJk+rRYZDF34ZVdH9TivF+zxnRuJeG8lQ7YmxuFaK5lRE2XbNTaHIOtT+VqH1Vmt5HyIAUs3Zu-pR4rAgCPmMZgbAgH5xAHVLI2BGA3mqHwMsooljXReYqOYF6OKMAAAIxJIN+uJrQ31Xq5mAkAD0np8DAOJegjRPI3AsDcIAA) to the file on **flems.io** causing problems with Mithrill 2.0 (lines 12 and 17)

Example, 
this line
`oninput: m.withAttr("value", function(value) {User.current.firstName = value}),`
should be changed to this line
`oninput: function (e) { User.current.firstName = e.target.value }`

Thank you for the great framework!

**Comment by CreaturesInUnitards** [comment]
@Manidos great catch! You should PR that :)

**Comment by Manidos** [comment]
> @Manidos great catch! You should PR that :)

Here's [link ](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcICqkBOAxA9tgLYB0AVmCADQgBmAljJagNqgB2AhkRGpjgFl8SaOUo1Y+doml8Abp2wACLBGUBeJcAA67JfqVR6YeKiUsAulV0HD+TkgAyx00toBXdgnpSAFAEotG1sDbAh4d2w9UjCAR3cIE18dPRC0nngAC2EzbRAAcQBRABU861S020ioXJBM+HgABzBUAHpWsKIAWjCTLs5G+hJMtXwAa3cBxpJJIlaB+lb3HDAy4MqDAHd6LIBhMJFpek4oFqV4bATyjYBff3WQkiyIdl8PL3gfV973KHhAlIbWyqbAkIwmJSaH5-EhITjwTgPWx3B43coPWCRMLSMzANEPKD2JBmd7ePz0JAApGhcKRaIkOIJJKAoH6DLZYlKPJFUrUalpaq1epNFrtTo9RLwfqDYajCZTGb4OYLJYrVp5JQAaiUFOurKU2z2BxenxOZwuV35ShRFUez1epM+fmh-yCto2IJmWJNkKULqtNuR6NtYE4cggJM8ZNeVPdNIiUSUMQg8UlySttnZOS5IAAChheXrWYKc8Lmm0OhBur0pQtZdhxpNGtNZvNBqq1GB1SAtSocF7sNj4CRdRmDHCEWZPZjByai0DDZl9sgTcdTmYLRB58j7rabrobiA0RxuLx0CDnCYxNQQJJpCb5Io+2pL-BfSz9FJ6OwdlP+4SHFfec5HoCBNkjD4vgCN0NjCBNol8PISGWNQunBeAymfUF0JIIgBjeKMnVeFDsFjfU-VpRMiEQkBOGQnA0JcLodirTDgEyMJaFqVpkB2btexIkckCoJQpFgMJ4QjJMGXwdxEDBb8xjRJRBIYbATAAOVPXsNQ1bVBKgThNNPXdbn8UyDH3dhD2PEAuB4PgQQIYhrwkKQZHgR9lCcwgiHfB4vx-VxHSguR2GECAAU9ACkF8MKIpIeELjAIT-HxW0QLAiDo2gj8Qjgukkxo2hfLYsc0ikMB3AAIyIX83EIqDIpg8jKggEhGjCcNpAAEQgWhOF+eAAnKoFPVDcMRrjVkrPI5SWFG6i8kM6rRBW6BMLyXB6HUt97IgPJ-G3SolpAb9Gjkkd2Au+AWHgABPRoIHURAAA94AsFhGkM2AIGyKARGwdRtt2pR9osMrpqBQKbuyoilF8ZrgCwgchxINTjJ4X12oRbAAHNwhIBQoASa1jtZYmEj-NRUZNdGdsxg6oZ3cmQlO9aoDBThVqgTaQEcIy9tPQ7WczGjzsuiXbu+zhfv+wH1AFiFwch1qDBhuS4a+BGkZRmc0cMxnsaeRQCeHSmIDJ0bbAt6nQX1unDfgLSeFGu5RYMU7qrk+ApBIb2GikO7Hueqrap2CHqBzABlMMDpAI6rQsCz9Csw8aEgGBo2YEAAEYADZUHz3OjyoE8HPQAX7tk4cKBvO8PK8pQq5r-yMtA8CGsgvx4pEMjKgKqiaLw78ueruTMIW5nPZorg5Fwl53En62Z7yREo7ytWOP6swAHJWnQ3ePY2MSJMQMwYhr9qjHYMYV9TkS8hBVYE9G5Pj6KvJIGjTDe-a2BMiMCQNiFOIRk6ogPKXcuZ5aLNlcredyD50CXzku1Tq-V6CvV8LvAAxLvXcKDEC+CQPgTEPBpD+2EPdR+IAD4uFVgYPIdCTB5FxFabEgMtZ+H7qyQeCEW5yREtRC8LhzIBlRPOJhvF4CtFQBSVhLU0gcLUFw14f8eFAj4UVAR8AhG+B8sQESf9EoNHUmIqGs1LLlDuFAuyp4+AzDAOIBB95ZDoGqlQqgV0bpeIDr7PQwASo4nCsQE4SgC6NFekoAAamoOEXAADceF8bfjMAAJgAAyRKsroMerdgDJLxqk3OWSomDV9kkzgr0ujbCQFkVAJSMmlISVZBe7B3BaEKakjJSgekAGZmk5PYPRVC6EtDoS6CYe6MBUDhXYBASpKT2CoB6T0kpkSEmNAcEgb8eMVktNySRRifQWJ+WANVWWYw8YNk8MSHBA0HmcASR47AnDc6RKUGAfARgkBKBwUgAFCTJCEmwKgHBfSIUJJ2WAGW91UDVUJLAMYiyinLNWeEjZWyAW7NQAADg+bnAArBst6UoRCSGwPCL4sypALNaUciZpzUDZHDMoYApKujksIFSqQqBblqBvnS3QuSOZaGhbC+FiLkVdLRb0pQxLXoHOGVLLQLy3kfK+T8v5AKkDPMIIDHoDh6DLFQH0jZHjqlgHoAALxxWq1CFqoXGAlQi0h0rTbdLlesxVWKdnsD2d68JCqEm1PqY0gApEq-2PspCqsudc2S7A7kQBTXq15Kj3lRM1RSbVgL7XYENTsk1ZrFXAsIGCiFfSnUwsMnC78gquiuqRSiz1azmm+pxYGolJKIDvU5XAblREaXzKjX43lLK1BxqRQm25YKIC4vnfOlpR4rAgBvmMZgbA7EVxAHVLI2BGDwOqHwMsooljXSuYqOYe6OKMAAAJpJIBkp9PRYAkAACytBvQezmdcaAPSenwMA4l6CNE8jcCwNwgA)to updated code on **flems.io**

Somebody needs to update the link in the tutorial [here](https://mithril.js.org/simple-application.html)
I don't know how to make a PR for it.

**Comment by isiahmeadows** [comment]
@Manidos Check out [this](https://help.github.com/en/articles/editing-files-in-another-users-repository). The docs files are all in [this directory](https://github.com/MithrilJS/mithril.js/tree/next/docs), and the file in question is [here](https://github.com/MithrilJS/mithril.js/blob/next/docs/simple-application.md).

And usually, when we say "PR", we use it as short for "pull request". It's much easier to type.

**Comment by Manidos** [comment]
I'm not sure if I need to post it here, but anyway. 
Here's pull request https://github.com/MithrilJS/mithril.js/pull/2403

**Comment by dead-claudia** [comment]
Linked PR was merged.
